spring.application.name=Labirinto_Literario

# Vai mandar pro arquivo .properts local para ler o arquivo de senha
spring.profiles.active=local

# criara o banco e instalando o driver
# Adicione allowPublicKeyRetrieval=true ao final da URL
spring.datasource.url=jdbc:mysql://localhost:3306/Labirinto_Literario?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# configuração de hibernate e jpa
# update: cria as tabelas se não existirem e atualiza se você mudar o código
spring.jpa.hibernate.ddl-auto=update

# depois da requisição vai exibir o sql no terminal
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect